### ISSUE TITLE
After adding someone as friend, their profile still appears in explorer gallery

### ISSUE THREAD

**Issue by BrianCFred** [PhitNest/phitnest#112]
Applies for profiles you've already sent a friend request to but haven't friended yet and profiles that have accepted your request.

**Comment by CaglarKullu** [comment]
Couldn't recreate the issue, I have added @JohnSiegel but it disappeared after adding even though JP hasn't accepted yet.

**Comment by JohnSiegel** [comment]
Related (possible duplicate) to #114

**Comment by uvaishzafri** [comment]
@hayleyw7  are you working on this? If not, then can I take this?

**Comment by hayleyw7** [comment]
> @hayleyw7 are you working on this? If not, then can I take this?

I'm not. It's all you! :)
