### ISSUE TITLE
Web Version -> after friending Regan and JP (showing friendship already exists), everyone else showing friendship sent

### ISSUE THREAD

**Issue by Aquahoya** [PhitNest/phitnest#114]

**Comment by JohnSiegel** [comment]
To reproduce:

1. Have two accounts that have not sent each other any friend requests
2. Send a friend request from one account to the other
3. Check that the account you have sent a friend request to is no longer shown on explore
4. From the account that received the friend request, check that the first account **IS** still shown on explore page.
5. From the account that received the friend request, accept the friend request
6. Check that neither account is shown on each other's explore page

**Comment by CaglarKullu** [comment]
When I sent a request to my other account the receiver disappeared.
When I checked with the receiver I could see the request and the sender in the explore page as the SS below
![image](https://github.com/PhitNest/phitnest/assets/97615706/8f2a5b18-9bdd-47d6-bf6b-49be9f7abb35)
When I tried to add I encountered an issue
![image](https://github.com/PhitNest/phitnest/assets/97615706/7be1c15b-93b9-45c7-8c91-0f8fcb3ddebe)

**Comment by JohnSiegel** [comment]
Closing because I could not reproduce
