### ISSUE TITLE
Exception on registration screen: "Build scheduled during frame."

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#118]
When the keyboard is visible on the registration screen and you scroll to dismiss it, an exception is thrown. Must be ran with console output to see error message.

**Comment by CaglarKullu** [comment]
Hi ! Could you please add an SS and which emulator did you use? I couldn't manage to replicating it @JohnSiegel

**Comment by CaglarKullu** [comment]
Couldn't reproduce so I am closing
