### ISSUE TITLE
Invalid Pool error

### ISSUE THREAD

**Issue by CaglarKullu** [PhitNest/phitnest#120]
![image](https://github.com/PhitNest/phitnest/assets/97615706/7f19ed2f-f3df-41a5-b249-f152eb36b265)
![image](https://github.com/PhitNest/phitnest/assets/97615706/9056c8b1-ddce-4825-b074-6414fba19b14)
It happened when db was resetting but maybe we need to add a more user-friendly error.
![image](https://github.com/PhitNest/phitnest/assets/97615706/15faae8e-8a82-408a-a4d0-d5a9b71a03cc)
phitnest\packages\dart-core\lib\features\aws\login\response.dart

**Comment by JohnSiegel** [comment]
Need to update github actions script so this runs
