### ISSUE TITLE
Json type error when trying to add friend

### ISSUE THREAD

**Issue by CaglarKullu** [PhitNest/phitnest#127]
![image](https://github.com/PhitNest/phitnest/assets/97615706/691b5b04-0e0e-4e9a-9f71-e5e667f2d014)

Json type error when trying to add friend

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/phitnest/assets/97615706/29d1cbe6-c508-4315-a0cd-415f190d5924)

**Comment by JohnSiegel** [comment]
Closing as I think this is fixed.
