### ISSUE TITLE
Add pull to refresh on explore page

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#136]
Currently, once you start the app all of the necessary data is fetched a single time from the backend. So once you have fetched the data, it will not refresh until you restart the app.

Add the ability to pull to refresh on the explore page. https://www.scaler.com/topics/pull-to-refresh-flutter/

This will be a multi-part task involving both front end and back end development.

First, implement a new API route to fetch all of the users on the explore page. This is already done in the API route `GET /home`, but that API route fetches all of the users friend requests and profile data as well, so we want a more targeted API route for just explore data. The API route should fetch the explore users the exact same way that `GET /home` does. You can name this new API route `GET /explore`. Read the readme file in the [api repo](https://github.com/PhitNest/api) for guidance.

Once you've written the API route, ping me and I'll deploy it to a dev environment.

Next you will start on the Flutter side by writing a function to invoke the API endpoint, and then the UI pull-to-refresh mechanics.

**Comment by JohnSiegel** [comment]
@Mounix99 @bcha92 This task will involve both Flutter and TypeScript development. I'd like for the two of you to work on this together.

**Comment by bcha92** [comment]
Hi, I've opened a PR for the GET /explore api route ☝️ . Can you please check if this works on AWS Lambda, [JP](@JohnSiegel)?

**Comment by JohnSiegel** [comment]
> Hi, I've opened a PR for the GET /explore api route ☝️ . Can you please check if this works on AWS Lambda, [JP](@JohnSiegel)?

Your API route is live on the dev environment. It is accessible with the `apps/mobile/lib/config/aws.dart` file on master branch.
