### ISSUE TITLE
Build an OpenAPI spec

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#139]
Build a spec for our REST API. The REST API is in `apps/backend/rest-api`. The OpenAPI specification docs can be found here: https://swagger.io/specification/

Commit the spec to the `docs` folder in the monorepo.

Start with a relatively vague and low-detail spec of every API route, then we will gradually improve it.

**Comment by CaglarKullu** [comment]
yaml file added now I will work on an express static page

**Comment by CaglarKullu** [comment]
doc added to master
