### ISSUE TITLE
Create "POST /report" API route

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#140]
In our recent iOS app store rejection, Apple requested us to create a feature for reporting/blocking users. To start, build an API route for blocking other users.

First, create a new type in `apps/backend/common/entities`. This will involve a few steps, first defining the typescript type for the report, then creating a dynamo DB parsing shape for it (there are many examples throughout the `entities` dir, and typescript should guide you), then creating a method for creating a new block entity in the DB.

DynamoDB requires each entity in the DB to have a pk (partition key) and an sk (sort key). Our pk and sk for reports will have the following format:
pk: USER#{sender of report id}
sk: REPORT#{user being reported id}

The data of the report will look like this:
```
type Report = {
  senderId: string;
  receiverId: string;
  reason: string;
  createdAt: Date;
};
```

Once you create a method for creating new reports in the DB, you will create an API route for creating reports. The API route will be `POST /report`

**Comment by bcha92** [comment]
I am to assume this will be a `private` API endpoint as the reporter will have to be a current user logged into the app?

**Comment by JohnSiegel** [comment]
The create function will look something like this:

```
export async function createReport(
  dynamo: DynamoClient,
  senderId: string,
  receiverId: string,
  reason: string
): Promise<void> {
  await dynamo.put({
    pk: userPk(receiverId),
    sk: `REPORT#${senderId}`,
    data: reportToDynamo({
      ...
    }),
  });
}
```

**Comment by JohnSiegel** [comment]
Also, remember to filter out reported users from `GET /explore`

**Comment by bcha92** [comment]
> The create function will look something like this:
> 
> ```
> export async function createReport(
>   dynamo: DynamoClient,
>   senderId: string,
>   receiverId: string,
>   reason: string
> ): Promise<void> {
>   await dynamo.put({
>     pk: userPk(receiverId),
>     sk: `REPORT#${senderId}`,
>     data: reportToDynamo({
>       ...
>     }),
>   });
> }
> ```

Shouldn't `pk` be the `senderId` instead of `receiverId` since sender is the one reporting the receiver?

**Comment by JohnSiegel** [comment]
Yes good catch @bcha92

**Comment by bcha92** [comment]
PR opened here: https://github.com/PhitNest/phitnest/pull/145

**Comment by JohnSiegel** [comment]
Good work!
