### ISSUE TITLE
Create UI component for reporting/blocking users

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#141]
In our recent iOS app store rejection, Apple informed us that we need a report/block user feature.

On the explore page, add a button in the top right corner for each user to "report user". This should open a modal where you can enter a reason for reporting users. The API is being worked on for this right now, so only the UI components need to be made for this task. Make the design simple, it does not need to look good, it just needs to work.

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/phitnest/assets/97615706/e7661a52-8af4-4b00-a41d-62289bea0d9b)
![image](https://github.com/PhitNest/phitnest/assets/97615706/8cc59935-23b3-485d-a108-65d54d234d66)
![image](https://github.com/PhitNest/phitnest/assets/97615706/9fce9911-552a-4663-a358-c08d302a4a6a)
Does this enough @JohnSiegel ?
