### ISSUE TITLE
Web version - the text for a button is not visible on cropping screen

### ISSUE THREAD

**Issue by priscilla-sin-yi** [PhitNest/phitnest#142]
The button in the bottom right has no (visible) text. I know you mentioned before that it's expected for the UI on the web app to be imperfect. But this one seemed worth flagging since it's more than alignment issues.

![Image](https://github.com/PhitNest/phitnest/assets/145619721/16f4d656-3d97-4b67-ad45-e9f10bfaa841)

**Comment by JohnSiegel** [comment]
Merging with #138 (duplicate)
