### ISSUE TITLE
Web version - my account photo on options page is showing as the last person I sent a friend request to

### ISSUE THREAD

**Issue by priscilla-sin-yi** [PhitNest/phitnest#143]
Expected behavior:
On the Options screen, I see my own profile photo

Actual behavior:
I saw JP's photo the first time (thought maybe it's a placeholder/default). Then after sending more friend requests, I saw Caglar's photo. So I think the photo of the last person I sent a friend request to is rendering on the Options screen - instead of my own profile photo.
(Update after deleting my account and creating another one - originally, my own profile photo shows on the Options screen. Then it changes to the photo of the last person i sent a friend request to)

![Image](https://github.com/PhitNest/phitnest/assets/145619721/2081d12c-622d-4566-88e8-5db2f347f7f3)
![Image](https://github.com/PhitNest/phitnest/assets/145619721/06adac8a-c27f-4343-9f12-a22af4105113)

**Comment by TurnerWilson** [comment]
Having the same issue on the mobile version

**Comment by JohnSiegel** [comment]
Identified a small mistake in the code and fixed it. Thanks for reporting!
