### ISSUE TITLE
Screen Swiping

### ISSUE THREAD

**Issue by IzzyBizzyCoding** [PhitNest/phitnest#154]
# Screen swiping
I can swipe to the next screen before I input anything. Meaning that I can go to the next page without actually putting my first and last name (as instructed by the first screen). 

## Current State
Having the names are important, and something that's been mentioned to reduce spam and to create better connections. If a user can swipe to the next screen, can they create a profile without including their name?

## Expected State
Users should not see the next screen until they've done the steps of their current screen (in this case upload a name)

## Steps to Reproduce
Provide step-by-step instructions on how to reproduce the bug. Include any necessary prerequisites or setup steps.
1. Click on "register" account
2. Swipe to the right using your finger

## Additional Information
N/A

## Images
![IMG_5521](https://github.com/PhitNest/phitnest/assets/87436915/b596c837-7959-4c3c-bbf0-8330f8442879)
png)

**Comment by JohnSiegel** [comment]
Fixed
