### ISSUE TITLE
There is no padding around the main widgets

### ISSUE THREAD

**Issue by CaglarKullu** [PhitNest/phitnest#156]
![image](https://github.com/PhitNest/phitnest/assets/97615706/b42fd78c-c8aa-42e9-af6f-728b8a42e17c)
We may consider adding some padding

**Comment by JohnSiegel** [comment]
Use your own judgement on spacing and alignment. As long as it works well enough to get App Store approval it's good for now.

**Comment by CaglarKullu** [comment]
Issue has resolved https://github.com/PhitNest/phitnest/pull/166
