### ISSUE TITLE
trying to log off and log in fall into endless loop

### ISSUE THREAD

**Issue by CaglarKullu** [PhitNest/phitnest#158]
![image](https://github.com/PhitNest/phitnest/assets/97615706/52442bf3-ddd0-4051-9ece-a10d3e2b7a1d)
![image](https://github.com/PhitNest/phitnest/assets/97615706/a8607c04-ac75-4bda-bf04-bc9e49ba06c8)

**Comment by JohnSiegel** [comment]
Fixed
