### ISSUE TITLE
Bottom Nav turns black

### ISSUE THREAD

**Issue by IzzyBizzyCoding** [PhitNest/phitnest#164]
When I match with someone the bottom nav turns black - low priority

Steps to reproduce
1. Go to explore page
2. Friend someone
3. Have them friend you back
4. Accept their request in the friends page (see congrats you've matched message and the bottom nav will turn black)

**Comment by JohnSiegel** [comment]
I don't understand the steps to reproduce. 

Step 2 is to send them a friend request

In step 3 they friend you back

In step 4 you send them another friend request? How? You're already friends.

With regards to the nav bar turning black, this should only occur when you are on the explore page and you send a friend request to someone who has already requested you. The nav bar shouldn't be turning black under any other circumstances, so if it is occurring on the friends page that is a bug.

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/phitnest/assets/97615706/e9e07834-f75f-4d2f-92e7-2ac7680f798d)
replicated.

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/phitnest/assets/97615706/74782dfa-511f-4c5e-b6fd-475e64290f5d)
Reverse Color state doesn't activated

**Comment by JohnSiegel** [comment]
Yep it should be turning black when you match with someone on the explore page.

**Comment by CaglarKullu** [comment]
Then I close the issue, we xan change the design later.
